name: Deploy Server

on:
  push:
    branches:
      - main

env:
  FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
  FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
  FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
  FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}
  FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
  FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
  FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: currency-converter
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Deploy backend
        run: npm run deploy
        working-directory: server
    

